config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/auth/facebook/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: :logout

  resource :dashboard, only: [:show]
  resources :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :provider, :uid, presence: true

  has_many :pins, dependent: :destroy

  def self.find_or_create_by_omniauth auth_params
    user = self.find_or_create_by(provider: auth_params.provider, uid: auth_params.uid) do |user|
      user.email = auth_params.info.email
      user.first_name = auth_params.info.first_name
      user.last_name = auth_params.info.last_name
      user.image = auth_params.info.image
    end

    user
  end

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by id: session["user.id"]
  end
  helper_method :current_user

  def signed_in?
    true if session["user.id"] && session["user.id"].present?
  end
  helper_method :signed_in?

  private

  def authenticate_user!
    unless current_user
      redirect_to root_path, alert: "You need to sign in first."
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    redirect_to dashboard_path if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by_omniauth auth_params
    session["user.id"] = user.id

    redirect_to dashboard_path, notice: "Signed in successfully"
  end

  def destroy
    session["user.id"] = nil
    redirect_to root_path, notice: "Signed out successfully"
  end

  private

  def auth_params
    request.env["omniauth.auth"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.haml
= "Hello #{current_user.email}"

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: "navigation" }
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{ "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1", type: "button" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
          
      = link_to "Pinboa.rd", root_path, class: "navbar-brand"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if signed_in?
          %li.active
            = link_to current_user.full_name, "#"

          %li
            = link_to new_pin_path do
              %i.glyphicon.glyphicon-plus
              New Pin

          %li
            = link_to "Logout", logout_path, method: :delete, "data-confirm" => "Are you sure?"

        - else
          %li.active
            = link_to "Login with Facebook", "/auth/facebook"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pinboa.rd
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/nav"

    .container.top70
      .row
        .col-lg-12
          = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true